# Generated by Django 5.2.7 on 2025-11-12 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_client_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id_catalogue', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2500)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(default='Non classé', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='shop.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(default=django.utils.timezone.now)),
                ('montant_total', models.DecimalField(decimal_places=4, max_digits=65)),
                ('mode_paiement', models.CharField(choices=[('OM', 'ORANGE_MONEY'), ('MOMO', 'MOBILE_MONEY'), ('CB', 'CARTE_BANCAIRE'), ('PAL', 'PAIEMENT_APRES_LIVRAISON')], default='OM', max_length=10)),
                ('statut', models.CharField(choices=[('P', 'PAYE'), ('EA', 'EN_ATTENTE'), ('A', 'ANNULE')], default='EA', max_length=10)),
                ('adresse_livraison', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('detail_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.detail_facture')),
                ('retrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.retrait')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('actif', models.CharField(choices=[('EN', 'EN_VENTE'), ('DV', 'DEJA_VENDU')], default='EN', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catalogue')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.facture')),
            ],
        ),
    ]
