# Generated by Django 5.2.7 on 2025-10-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=250)),
                ('tel', models.IntegerField(max_length=15)),
                ('adresseMail', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
