# Generated by Django 5.2.7 on 2025-10-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adresseMail',
            new_name='email',
        ),
    ]
