# Generated by Django 5.2.7 on 2025-11-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alertes_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='langue',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='localisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='maj_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notif_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='partage_donnees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='theme_sombre',
            field=models.BooleanField(default=False),
        ),
    ]
