# Generated by Django 5.2.7 on 2025-11-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_client_alertes_email_client_langue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(default='000000000000000', max_length=15),
        ),
    ]
